<?php

        global $sql_prefix,$db,$tplname;

        /* Affichage des stages */
#        $requete="SELECT login FROM jj_utilisateur order by login";
#        $result = $db->query($requete);
#        echo $db->error;
?>

<form id='pass-form' action='<?php echo $url; ?>/pass.php' method="POST">
	<h2>Nouveau mot de passe de <?php echo $_SESSION['login']; ?></h2>
<!--	<label for='login'>Login : <?php # echo $_SESSION['login']; ?></label>-->
	<input type='hidden' name='login' value='<?php echo $_SESSION['login']; ?>' /><br />
<!--	<select name='login'>
	<?php
#		while ($array = $result->fetch_array()) {
#			$login = $array['login'];
#			echo "<option value='$login'>$login</option>";
#       	}
	?>
	</select> -->
	<div>
	<input type='password' name='pass' id='pass' /><br />
	</div>
	
	<input type='submit' name='submit' value='Modifier' />
</form>

<script>
$(function() {
    $("#pass-form div").append("<div id='letterViewer'>");
    $("#pass").keypress(function(e) {
        $("#letterViewer")
            .html(String.fromCharCode(e.which))
            .fadeIn(200, function() {
                $(this).fadeOut(200);
            });        
    });
});
</script>
