<form id='stagiaireadd' action='<?php "?page=stagiaire&action=create"; ?>' method="POST">
	<label for='nom'>Nom :</label>
	<input type='text' name='nom' class="validate[required,custom[onlyLetterSp]]" /><br />
	<label for='prenom'>Pr&eacute;nom :</label>
	<input type='text' name='prenom' class="validate[required,custom[onlyLetterSp]]" /><br />
	<label for='sexe'>Sexe :</label>
	<input type="radio" name="sexe" value="M" />Homme
	<input type="radio" name="sexe" value="F" checked='checked' />Femme<br />
	<input type='submit' name='submit' value='Ajouter' />
</form>
<script>
$(document).ready(function(){
    $("#stagiaireadd").validationEngine();
   });
</script>