		<div id="about">
			<h2>G&eacute;n&eacute;ralit&eacute;s :</h2>
			<ul>
				<li><b>Auteur :</b> Adminrezo / Nicolas Dewaele</li>
				<li><b>Mises à jour :</b> NautilusWeb</li>
				<li><b>Licence :</b> <a href='LICENCE.txt'>Logiciel libre sous licence GPLv3</a></li>
				<li><b>Application :</b> <?php echo $sitename; ?></li>
				<li><b>Version :</b> <?php echo $version; ?></li>
			</ul>
			<h2>Navigateurs utilisables :</h2>
			<ul>
				<li>Mozilla Firefox (26.0 et +)</li>
				<li>Google Chrome (27 et +)</li>
			</ul>			
			<h2>Modules et librairies utilis&eacute;es</h2>
			<ul>
				<li>JQuery</li>
				<li>JQuery Validation Engine (Fr)</li>
				<li>PHP 5.2 Minimum</li>
				<li>Classes et librairies : DateTime, MySQLi, Hash</li>
			</ul>			
		</div>
