<!--
	KeepassWeb, un gestionnaire de mots de passe libre
	Auteur : Nicolas Dewaele
	Site Web : http://adminrezo.fr/
-->

<!--
	Theme Copper :
	Auteur : Nicolas Dewaele
	Site Web : http://adminrezo.fr/
-->

<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
	<title><?php echo $sitename." - v. ".$version; ?></title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=100,chrome=1">
	<meta name="description" content="Statistiques Jolijeune">
	<meta name="author" content="Nicolas Dewaele">
	<link rel="shortcut icon" type="image/png" href="<?php echo "$dir/tpl/$tplname$favicon"; ?>">
	<meta name="viewport" content="width=device-width">

	<link rel="stylesheet" href="<?php echo "$dir/tpl/$tplname$css"; ?>">
	<link rel="stylesheet" href="<?php echo "$dir/tpl/".$tplname."/css/print.css"; ?>" media='print'>
	<link rel="stylesheet" href="<?php echo "$dir/tpl/$tplname/css/validationEngine.jquery.css"; ?>">
	<!-- Autocomplete -->
	<style type="text/css">
	.autocomplete-suggestions { border: 1px solid #999; background: #FFF; overflow: auto; }
	.autocomplete-suggestion { padding: 2px 5px; white-space: nowrap; overflow: hidden; text-align: left;}
	.autocomplete-selected { background: #F0F0F0; }
	.autocomplete-suggestions strong { font-weight: normal; color: #3399FF; }
	.autocomplete-group { padding: 2px 5px; }
	.autocomplete-group strong { display: block; border-bottom: 1px solid #000; }
	</style>

	<script src="lib/jquery.min.js"></script>
	<script src="lib/jquery.validationEngine-fr.js" type="text/javascript" charset="utf-8"></script>
	<script src="lib/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
	<script src="lib/calculs.js" type="text/javascript" charset="utf-8"></script>
	<!-- Autocomplete -->
	<script src="lib/jquery.autocomplete.min.js" type="text/javascript"></script>


</head>
<body>
	<div id="page">
		<a href='?'><div id="logo"></div></a>
