<div id='home'>
	<ul>
		<li><a href='?page=stagiaire'><img src='tpl/<?php echo $tplname; ?>/img/stagiaires.svg' alt='Curistes' /></a> <a href='?page=stagiaire'>Curistes</a></li>
		<li><a href='?page=recherche'><img src='tpl/<?php echo $tplname; ?>/img/stagiaires.svg' alt='Recherche' /></a> <a href='?page=recherche'>Recherche</a></li>
		<br>
		<li><a href='?page=stage'><img src='tpl/<?php echo $tplname; ?>/img/stage.svg' alt='Cures' /></a> <a href='?page=stage'>Cures</a></li>
		<br><br>
		<li><a href='?page=deconnexion'><img src='tpl/<?php echo $tplname; ?>/img/deconnexion.svg' alt='D&eacute;connexion' /></a> <a href='?page=deconnexion'>D&eacute;connexion</a></li>
	</ul>
</div>