<?php
if (loggedIn()) {
	echo "<header>
			<nav>
				<ul>
					<li><a href='?page=home'><img src='tpl/$tplname/img/home.png' alt='Accueil' title='Accueil' /></a></li>
					<li><a href='?page=recherche'><img src='tpl/$tplname/img/stagiaires.png' alt='Curistes' title='Curistes' /></a></li>
					<li><a href='?page=stage'><img src='tpl/$tplname/img/stage.png' alt='Cure' title='Cures' /></a></li>
					<li><a href='javascript:window.print()'><img src='tpl/$tplname/img/print.png' alt='Imprimer' title='Imprimer' /></a></li>
					<li><a href='?page=deconnexion'><img src='tpl/$tplname/img/deconnexion.png' alt='D&eacute;connexion' title='Sortie' /></a></li>
				</ul>
			</nav>
		</header>";
} ?>
